import 'package:firestore_odm/firestore_odm.dart';
import 'package:dto/schema.dart';
import 'package:dto/models/patient.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:minimed/constants/colors.dart';
import 'package:minimed/constants/fonts.dart';
import 'package:minimed/constants/style.dart';
import 'package:minimed/screens/main_screen/main_screen.dart';
import 'package:minimed/widget/action_button.dart';
import 'package:minimed/widget/main_background.dart';
import 'package:minimed/widget/my_form_field.dart';

class AddNewPatient extends StatefulWidget {
  const AddNewPatient({super.key});
  static const String routeName = '/addnewpatient';

  @override
  State<AddNewPatient> createState() => _AddNewPatientState();
}

class _AddNewPatientState extends State<AddNewPatient> {
  String firstName = "";
  String lastName = "";
  String phoneNumber = "";
  DateTime? dateOfBirth;
  String email = "";
  String gender = "";

  @override
  Widget build(BuildContext context) {
    return  MainBackground(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Text(
                "Ajouter un nouveau patient",
                style: titleText,
              ),

              const SizedBox(height: 30),

              MyFormField(
                  label: "Nom",
                  icon: Icons.badge_outlined ,
                  isToHide: false,
                  onChanged: (value) { lastName = value; },
              ),

              MyFormField(
                label: "Prénom",
                icon: Icons.person_outlined ,
                isToHide: false,
                onChanged: (value) { firstName = value; },
              ),

              MyFormField(
                  label: "Numéro de téléphone",
                  icon: Icons.phone_iphone_outlined,
                  isToHide: false,
                onChanged: (value) { phoneNumber = value; },
              ),

              GestureDetector(
                onTap: () async {
                  DateTime? pickedDate = await showDatePicker(
                    context: context,
                    initialDate: DateTime.now(),
                    firstDate: DateTime(1900),
                    lastDate: DateTime.now(),
                  );

                  if (pickedDate != null) {
                    setState(() {
                      dateOfBirth = pickedDate;
                    });
                  }
                },
                child: AbsorbPointer(
                  child: MyFormField(
                    label: dateOfBirth == null ? "Date de naissance" : "${dateOfBirth!.day}/${dateOfBirth!.month}/${dateOfBirth!.year}",
                    icon: Icons.calendar_month_outlined,
                    isToHide: false,
                    onChanged: (value) {},

                  ),
                ),
              ),

              MyFormField(
              label: "Email de contact",
              icon: Icons.email,
              isToHide : false,
                onChanged: (value) { email = value; },
              ),

              DropdownButtonFormField<String>(
                initialValue: gender.isEmpty ? null : gender,

                items: const
                [
                  DropdownMenuItem(child: Text('Femme'), value: 'Femme'),
                  DropdownMenuItem(child: Text('Homme'), value: 'Homme'),
                ],

                onChanged: (value) {
                  setState(() {
                    gender = value ?? '';
                  });
                },
                decoration: InputDecoration(
                  prefixIcon: Icon(Icons.wc_outlined, color: iconFormColor),
                  hintText: "Sexe",
                  hintStyle:  TextStyle(
                    fontSize: fontSizeS,
                    color: textFormColor,
                  )
                )
                ),

              SizedBox(height: 30,),

              ActionButton(
                  label:"Enregistrer un nouveau patient",
                  onTap: () async {
                    final db = FirestoreODM(appSchema, firestore: FirebaseFirestore.instance);

                    await db.users(FirebaseAuth.instance.currentUser!.uid).patients.insert(
                        Patient(
                          id: FirestoreODM.autoGeneratedId,
                          firstName: firstName,
                          lastName: lastName,
                          dateOfBirth: dateOfBirth!,
                          gender: gender,
                          email: email,
                          phoneNumber: phoneNumber,
                          createdAt: DateTime.now(),
                        ),
                    );

                    if(!context.mounted) return;

                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(
                        content: Text('patient added'),
                      ),
                    );

                    Navigator.pushNamed(context, MainScreen.routeName);

                  }
              ),
            ],
          ),
        )
    );
  }
}
